-- Та же схема для SQLite: только для локальной разработки и автотестов (tools/test-api.sh).
-- В бою используется MySQL: sql/schema.mysql.sql.

CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  login TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS site (
  id INTEGER PRIMARY KEY,
  cafe TEXT NOT NULL, settings TEXT NOT NULL, ticker TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS dishes (
  id TEXT PRIMARY KEY, position INTEGER NOT NULL DEFAULT 0, name TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT '', description TEXT, weight TEXT NOT NULL DEFAULT '',
  price TEXT NOT NULL DEFAULT '', old_price TEXT, tag TEXT NOT NULL DEFAULT '', photo TEXT,
  active INTEGER NOT NULL DEFAULT 1
);
CREATE TABLE IF NOT EXISTS events (
  id TEXT PRIMARY KEY, event_date TEXT NOT NULL, time_start TEXT NOT NULL DEFAULT '', time_end TEXT NOT NULL DEFAULT '',
  title TEXT NOT NULL, description TEXT, price TEXT NOT NULL DEFAULT '', tag TEXT NOT NULL DEFAULT '', photo TEXT,
  highlight INTEGER NOT NULL DEFAULT 0, active INTEGER NOT NULL DEFAULT 1
);
CREATE TABLE IF NOT EXISTS slides (
  id TEXT PRIMARY KEY, position INTEGER NOT NULL DEFAULT 0, type TEXT NOT NULL,
  enabled INTEGER NOT NULL DEFAULT 1, config TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS media (
  id INTEGER PRIMARY KEY AUTOINCREMENT, path TEXT NOT NULL UNIQUE, original_name TEXT NOT NULL DEFAULT '',
  mime TEXT NOT NULL, width INTEGER NOT NULL DEFAULT 0, height INTEGER NOT NULL DEFAULT 0,
  size INTEGER NOT NULL DEFAULT 0, has_alpha INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS options (name TEXT PRIMARY KEY, value TEXT NOT NULL);
